# Generated by Django 4.2.2 on 2023-06-17 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('vendor_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name_plural': 'PurchaseOrders',
                'ordering': ['id'],
            },
        ),
    ]
