# Generated by Django 4.2.2 on 2023-06-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_alter_purchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='order_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
