# Generated by Django 4.2.2 on 2023-06-18 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_purchaseorder_order_name_alter_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Description')),
                ('length', models.FloatField(verbose_name='Length')),
                ('width', models.FloatField(verbose_name='Width')),
                ('height', models.FloatField(verbose_name='Height')),
                ('weight', models.FloatField(verbose_name='Weight')),
                ('volume', models.FloatField(verbose_name='Volume')),
                ('supplier_ids', models.ManyToManyField(to='purchase.vendor')),
            ],
        ),
    ]
