# Generated by Django 4.2.2 on 2023-06-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_product_available_quantity_product_prod_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Available Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='reserved_quantity',
            field=models.IntegerField(default=0, null=True, verbose_name='Reserved Quantity'),
        ),
    ]
