# Generated by Django 4.2.2 on 2023-06-18 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_alter_product_available_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['id'], 'verbose_name_plural': 'Vendors'},
        ),
    ]
